.\" whoa these are comments
.\" man page for metar(1)
.\" nroff -man -Tascii metar.1 | less

.TH METAR 1 "July 2017" "metar 1.95" "User Commands" "metar"
.SH NAME
metar \- fetch aerodrome routine meteorological reports (METAR) and present the information within.


.SH SYNOPSIS
.B metar [-dehnrsv]
.I station[s]
.B ...


.SH DESCRIPTION
METAR is the name of the code for an aerodrome routine meteorological report.
.B metar
fetches the information of current weather conditions of specified weather stations and decodes them into trivially readable format.

METAR is a way to display a comprehensive overview of current weather conditions in a compact report.
Because METAR is primarily used by aviation we refer to weather stations with the codes of airports when we want to get a report from a certain site.
The codes are assigned by ICAO (International Civil Aviation Organization) and most (but not all) ICAO-coded aerodromes have a METAR reporting system whose data can be accessed for example with this tool. Please check the end of this file to obtain a list of all airport ICAO codes.

Please remember that the exact weather conditions at your location may differ greatly from the observation data unless you are located in the immediate vicinity of the observation site. Many times, the information is nonetheless a passable approximation of the weather conditions also for the surrounding area.

By default the program gets METAR data provided by NOAA (National Oceanic and Atmospheric Administration) with
.BR libcurl (3).
There are a couple of formats to print out the decoded data.


.SH OPTIONS
Options can be combined:
.B metar \-re
.I station
would give you raw METAR data (-r) and extended brief report (-e). Adding
.B \-d
would add full decoded report. You can also give more than one station and get the desired report from each.

.IP -b
Briefly decode retrieved METAR report with the most essential information on a single line (no line breaks). This will print all weather conditions but not the longer explanations resulting from e.g. NOSIG, CAVOK or SNOCLO.

This is the default behavior when no output options are given.

.IP -d
Decode retrieved METAR reports with a multi-line summary. This gives all information that
.B metar
can provide:
.br
* observation station, day, time
.br
* wind direction, speed (also gust if it differs from speed)
.br
* visibility
.br
* temperature, dew point
.br
* pressure
.br
* clouds
.br
* other conditions.

.IP -e
Briefly decode with extra information. Implies
.B -b
and prints barometric pressure, clouds, and other non-weather stuff in addition.

.IP -h
Show quick usage guide.

.IP -n
If implied,
.B metar
will not attempt to convert wind units. By default it always converts knots (KT) to metres per second upon detecting such a unit.

.IP -r
Print raw METAR data string.

.IP -v
Show verbose information during report fetching and parsing.


.SH FILES
.B metar
doesn't use any files (even config ones).


.SH ENVIRONMENT
If the environment variable
.I METARURL
is set,
.B metar
will attempt to download the weather report from that location, instead of default. The value of
.I METARURL
will be postfixed with the capitalized station ID, followed by the .TXT extension.


.SH DIAGNOSTICS
.B METAR station FOOO not found in NOAA data.
.br
.B metar
was not able to retrieve information for station FOOO. Most likely you requested non-existent station, since CURL gives its own errors if it can't fetch data.

.B CURL error while retrieving URL
.br
.BR libcurl (3)
was unable to get requested URL. Most likely you were not connected to internet or you hadn't set your proxy correct. Refer to libcurl documentation about given error code.


.SH TODO
Test and sanitize
.B metar
's handling of user input.

So far,
.B metar
will also not parse:
.br
* visibilities given in fractions (e.g. 1/4SM)
.br
* trend forecasts and related (BECMG, TEMPO, PROB)
.br
* runway stuff.


.SH AUTHOR
This version of
.B metar
and the man page is made by Antti Louko <antti@may.fi>.

Original author of
.B metar
and the first version of man page is Kees Leune <kees@leune.org>.


.SH SEE ALSO
Raw METAR data file directory:
.B http://tgftp.nws.noaa.gov/data/observations/metar/stations

List of weather observation stations, including possible ICAO airport codes:
.B http://tgftp.nws.noaa.gov/data/nsd_bbsss.txt


.SH REFERENCES
.B WMO-No. 306
.br
Manual on Codes: International Codes, Volume I.1,
.I FM 15-XV METAR.
.br
World Meteorological Organization (2011 u. 2015).

.B FMH-1
.br
Federal Meteorological Handbook No.1 Surface Weather Observations & Reports
.I Ch. 12: Coding
.br
OFCM, U.S. Dept. of Commerce/NOAA (2005).
