.\" whoa these are comments
.\" man page for metar(1)
.\" nroff -man -Tascii metar.1 | less

.TH METAR 1 "December 2010" "" "User Commands" "metar"
.SH NAME
metar \- fetch and format METAR weather reports

.SH SYNOPSIS
.B metar [-dehnrsv]
.I station
.B ...

.SH DESCRIPTION
.B metar
fetches the information of current weather conditions of specified weather stations and optionally decodes them into more easily readable format.

METAR format is a way to display a comprehensive overview of weather in a compact report.
Because METAR is widely used by aviation we refer to weather stations with the codes of airports when we want to get a report from a certain site.
The codes are assigned by ICAO (International Civil Aviation Organization) and most (but not all) ICAO-coded aerodromes have a METAR reporting system whose data can be accessed for example with this tool. Please check the end of this file to obtain a list of all airport ICAO codes.

By default the program gets METAR data with
.BR libcurl (3)
provided by NOAA (National Oceanic and Atmospheric Administration). There are a couple of ways to decode the data, if desired.

.SH OPTIONS
Options can be combined:
.B metar \-re
.I station
would give you raw METAR data and extended brief report. Adding
.B \-d
would add full decoded report. You can also give more than one station and get desired report from each.

.IP -b
Decode retrieved METAR report with the most essential information on a single line (no line breaks). Since we wanted just a brief report, this will print all weather conditions but not e.g. NOSIG, CAVOK (although it sets the visibility to be > 10 km) or SNOCLO.

This is the default when no output options are given.

.IP -d
Decode retrieved METAR reports with a multi-line summary. This gives all information that
.B metar
can provide:
.br
* observation station, day, time
.br
* wind direction, speed (gust if it differs from speed)
.br
* visibility
.br
* temperature, dew point
.br
* pressure
.br
* clouds
.br
* other conditions.

.IP -e
Implies
.B -b
and gives some extra information: barometric pressure, clouds and other non-weather stuff that
.B -b
won't print.

.IP -h
Show quick usage guide.

.IP -n
If implied,
.B metar
will not attempt to convert wind units.

.IP -r
Print raw METAR data string.

.IP -v
Show what's going on during report fetching and parsing.

.SH FILES
.B metar
doesn't use any files (even config ones).

.SH ENVIRONMENT
If the environment variable
.I METARURL
is set,
.B metar
will attempt to download the weather report from that location, instead of default. The value of
.I METARURL
will be postfixed with the capitalized station ID, followed by the .TXT extension.

.SH DIAGNOSTICS
.B METAR station FOOO not found in NOAA data.
.br
.B metar
was not able to retrieve information for station FOOO. Most likely you requested non-existent station, since CURL gives its own errors if it can't fetch data:

.B CURL error while retrieving URL
.br
.BR libcurl (3)
was unable to get requested URL. Most likely you were not connected to internet or you hadn't set your proxy correct. Refer to libcurl documentation about given error code.

.SH BUGS
.B metar
won't sanitize user input.

So far,
.B metar
will also not parse:
.br
* visibilities given in fractions (e.g. 1/4SM)
.br
* forecasts (TEMPO, PROB, BECMG)
.br
* runway stuff

Also automatic mapping between ICAO code and station location would be nice so user wouldn't have to know station codes at all...

.SH AUTHOR
Original author of
.B metar
and this man page is Kees Leune <kees@leune.org>.
Man page rewritten and
.B metar
further improved by Antti Louko <antti@may.fi>.

.SH SEE ALSO
List of raw METAR datafiles:
.B http://weather.noaa.gov/pub/data/observations/metar/stations

List of ICAO airport codes:
.B http://weather.noaa.gov/data/nsd_bbsss.txt

